apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag12d-sep17-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag12d-sep17-2:c8a699a6eb06bc705812cfa42b29861e64cb0241@sha256:37ae152aad9c7dc05e2b9ef49b5aa2f6c1d4e4fa473f50ac8b17c6d02b32b808 # use pre-built to bootstrap 
          name: app-inference
